# Generated by Django 4.0.4 on 2022-06-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at', 'payment_status']},
        ),
    ]
